import { Roboto } from "next/font/google";
import "./styles/globals.css";

import Header from "../components/GlobalComponents/Header";
import Footer from "../components/GlobalComponents/Footer";

const inter = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Oral de Lohan",
  description: "Generated by create next app",
  icons: {
    icon: "/icones/studient.ico",
    apple: "/icones/studient.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-black`}>
        <Header />        
        {children}
        <Footer />
      </body>
    </html>
  );
}
